import catchErrors from "../utils/catchErrors";

export const createEmployeeHandler = catchErrors(async (req, res) => {});
